### ISSUE TITLE
sign in

### ISSUE THREAD

**Issue by mp1pro** [maxccpage/Jamming#1]
Very intuitive sign in screen. That makes the app more professional and functional. When I click the 'sign in' button, the accessToken is retreived but the screen options does not update. That is because we did not change the state for `signedIn` to true in `getAccessToken()`

```
    this.setState({
         signedIn: true
    });
```

**Comment by maxccpage** [comment]
Thanks! Can you elaborate a little more on why 'sign in' is not working? I've fixed the state and thats not the only issue, I have a hunch it could be an issue with my redirect uri - having a "callback/" endpoint maybe. Thoughts?

**Comment by mp1pro** [comment]
We would have to resolve the issue through live chat. For further help, contact a react adviser at http://codecademy.com
